services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    container_name: homepage
    ports:
      - 20000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
    env_file: .env
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.moneten.cc,192.168.178.125:20000 # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      PUID: $PUID
      PGID: $PGID
