---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Media:
    - Redlib:
        - abbr: RE
          icon: sh-redlib-light.png
          href: "{{HOMEPAGE_VAR_BM_REDLIB}}"
    - Invidious:
        - abbr: YT
          icon: sh-invidious-light.png
          href: "{{HOMEPAGE_VAR_BM_INVIDIOUS}}"
    - Glance:
        - abbr: GL
          icon: sh-glance-light.png
          href: "{{HOMEPAGE_VAR_BM_GLANCE}}"

- Dev:
    - Github:
        - abbr: GH
          icon: sh-github-light.png
          href: https://github.com/
    - Coolify:
        - abbr: CO
          icon: sh-coolify-light.png
          href: "{{HOMEPAGE_VAR_BM_COOLIFY}}"
    - Deployment:
        - abbr: DE
          icon: si-svelte
          href: "{{HOMEPAGE_VAR_BM_DEPLOYMENT}}"

- Tools:
    - IT Tools:
        - abbr: IT
          icon: sh-it-tools-light.png
          href: "{{HOMEPAGE_VAR_BM_ITTOOLS}}"
    - Bento PDF:
        - abbr: BP
          icon: sh-bentopdf-light.png
          href: "{{HOMEPAGE_VAR_BM_BENTOPDF}}"
    - Vert:
        - abbr: Vert
          icon: sh-vert-light.png
          href: "{{HOMEPAGE_VAR_BM_VERT}}"
