---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/



title: "{{HOMEPAGE_VAR_TITLE}}"

background:
  image: https://www.solidbackgrounds.com/images/3840x2160/3840x2160-black-solid-color-background.jpg 
#  #brightness: 1
#  #blur: xs

color: gray

#quicklaunch:
#  searchDescriptions: true
#  hideInternetSearch: true
#  showSearchSuggestions: true
#  hideVisitURL: true
#  provider: custom # google, duckduckgo, bing, baidu, brave or custom
#  url: "{{HOMEPAGE_VAR_SEARCH_URL}}"
#  target: _blank

target: _blank

theme: dark

disableIndexing: true

disableCollapse: true

headerStyle: underlined

layout:
# System Tab
  Hosts:
    tab: System
    style: row
    columns: 2
  
  Monitoring:
    tab: System
    style: column

  Networking:
    tab: System
    style: column
  
  Management:
    tab: System
    style: column

# Media Tab
  Mediaserver:
    tab: Media
    style: row
    columns: 3

  File Storage:
    tab: Media
    style: row
    columns: 3

  Media Automation:
    tab: Media
    style: row
    columns: 3

  Calendar:
    tab: Media
    style: row
    columns: 2

# Services Tab
  Gaming:
    tab: Services
    style: column

  Finance:
    tab: Services
    style: column
    columns: 3

  Productivity:
    tab: Services
    style: column