---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/


- resources:
    cpu: false
    memory: false

- logo:
    icon: homepage

- greeting:
    text_size: lg
    text: Homelab

#- search:
#    provider: custom # google, duckduckgo, bing, baidu, brave or custom
#    url: "{{HOMEPAGE_VAR_SEARCH_URL}}"
#    target: _blank

- datetime:
    text_size: xm
    format:
      timeStyle: short

#- openmeteo:
#    label: "{{HOMEPAGE_VAR_CITY}}" # optional
#    latitude: "{{HOMEPAGE_VAR_LATITUDE}}"
#    longitude: "{{HOMEPAGE_VAR_LONGITUDE}}"
#    timezone: Europe/Berlin # optional
#    units: metric # or imperial
#    cache: 5 # Time in minutes to cache API responses, to stay within limits
#    format: # optional, Intl.NumberFormat options
#      maximumFractionDigits: 1